apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  user: YWRtaW4=
  pass: MWYyZDFlMmU2N2Rm # user 和 pass 都是经过 base64 转码的

#   $ echo -n 'admin' | base64
# YWRtaW4=
# $ echo -n '1f2d1e2e67df' | base64
# MWYyZDFlMmU2N2Rm

# $ kubectl get secrets
# NAME           TYPE                                DATA      AGE
# user          Opaque                                1         51s
# pass          Opaque                                1         51s