apiVersion: v1
kind: Pod
metadata:
  name: nginx-share-pid
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx
  - name: alpine
    image: alpine
    stdin: true
    tty: true

# kubectl create -f share-pid-pod.yaml
# kubectl attach -it nginx-share-pid -c alpine
# kubectl attach -it nginx-share-pid -c alpine
# ps ax