apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  selector:
    matchLabels:
      app: echo-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-deployment
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["/bin/sh"]
        args:
        - "-c"
        - "while true; do echo '{\"content\":\"hello\"}'; sleep 3;done"
