apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-replica
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-replica
    spec:
      initContainers:
      - name: alpine
        image: alpine
        volumeMounts:
        - name: share-volume
          mountPath: /pod-data
        command: ["/bin/sh"]
        args: ["-c", "echo hello from init container > /pod-data/index.html"]
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: share-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: share-volume
        hostPath:
          path: /data